## Data Aggregation using AdventureWorks Database
--------------

In [1]:
import numpy as np
import pandas as pd
import pyodbc
cnxn = pyodbc.connect(driver='{SQL Server Native Client 11.0}',
                      server='LAPTOP-2DK08FTD\SQLEXPRESS', 
                      database='AdventureWorksDW2017',               
                      trusted_connection='yes')

In [2]:
sql = """SELECT FF.FinanceKey,DD.FullDateAlternateKey,DO.OrganizationName,DDep.DepartmentGroupName,DS.ScenarioName, DA.AccountDescription, DA.AccountType,FF.Amount

FROM FactFinance as FF JOIN DimDate as DD ON FF.DateKey = DD.DateKey
JOIN DimOrganization AS DO
ON FF.OrganizationKey = DO.OrganizationKey
JOIN DimDepartmentGroup AS DDep
ON FF.DepartmentGroupKey = DDep.DepartmentGroupKey
JOIN DimScenario AS DS
ON FF.ScenarioKey = DS.ScenarioKey
JOIN DimAccount AS DA
ON FF.AccountKey = DA.AccountKey
"""

In [3]:
data = pd.read_sql(sql,cnxn)

In [4]:
data['FullDateAlternateKey']= pd.to_datetime(data['FullDateAlternateKey'])

In [5]:
data['TransactionYear'] =pd.DatetimeIndex(data['FullDateAlternateKey']).year

In [6]:
data.head()

,FinanceKey,FullDateAlternateKey,OrganizationName,DepartmentGroupName,ScenarioName,AccountDescription,AccountType,Amount,TransactionYear
0,1,2010-12-29,Northeast Division,Corporate,Actual,Salaries,Expenditures,22080.0,2010
1,2,2010-12-29,Northeast Division,Corporate,Budget,Salaries,Expenditures,20200.0,2010
2,3,2010-12-29,Northeast Division,Corporate,Budget,Payroll Taxes,Expenditures,2000.0,2010
3,4,2010-12-29,Northeast Division,Corporate,Actual,Payroll Taxes,Expenditures,2208.0,2010
4,5,2010-12-29,Northeast Division,Corporate,Actual,Employee Benefits,Expenditures,1546.0,2010

In [7]:
data.groupby(['AccountType','AccountDescription','TransactionYear']).agg({'Amount':np.sum})

                                                           Amount
AccountType AccountDescription       TransactionYear
Assets      Allowance for Bad Debt   2010                21704.06
                                     2011               728735.78
                                     2012              1138665.85
                                     2013              1340118.55
            Buildings & Improvements 2010               199257.40
...                                                           ...
Revenue     Other Income             2013               145364.20
            Trade Sales              2010              1403164.82
                                     2011             48114780.58
                                     2012             35958587.59
                                     2013             42628185.20

[281 rows x 1 columns]

In [8]:
data.groupby(['AccountType','AccountDescription','TransactionYear']).agg({'Amount':np.sum}).unstack()

                                             Amount                            \
TransactionYear                                2010         2011         2012
AccountType AccountDescription
Assets      Allowance for Bad Debt         21704.06    728735.78   1138665.85
            Buildings & Improvements      199257.40   2475051.42   3521376.09
            Cash                          759504.79  33247692.29  53246589.35
            Construction In Progress       22057.09    274867.30    391014.52
            Deferred Taxes                166846.85   5461876.01   8459638.86
...                                             ...          ...          ...
Revenue     Gain/Loss on Sales of Asset    -2984.20    -39720.65    -58726.23
            Intercompany Sales             41603.64   2095377.92   1697584.69
            Interest Income                 2433.67     32405.60     47995.92
            Other Income                    4989.36    -21256.92     94086.81
            Trade Sales                  1403164.82  48114780.58  35958587.59


TransactionYear                                 2013
AccountType AccountDescription
Assets      Allowance for Bad Debt        1340118.55
            Buildings & Improvements      4465514.57
            Cash                         59439815.62
            Construction In Progress       496081.66
            Deferred Taxes                9957982.22
...                                              ...
Revenue     Gain/Loss on Sales of Asset    -78577.60
            Intercompany Sales            1901824.53
            Interest Income                 64167.09
            Other Income                   145364.20
            Trade Sales                  42628185.20

[71 rows x 4 columns]

In [9]:
summary = data.groupby(['AccountType','AccountDescription','TransactionYear']).agg({'Amount':np.sum}).unstack()

In [10]:
pd.get_option("display.max_rows")

60

In [11]:
pd.set_option("display.max_rows",120)

In [12]:
summary

                                                         Amount               \
TransactionYear                                            2010         2011
AccountType  AccountDescription
Assets       Allowance for Bad Debt                    21704.06    728735.78
             Buildings & Improvements                 199257.40   2475051.42
             Cash                                     759504.79  33247692.29
             Construction In Progress                  22057.09    274867.30
             Deferred Taxes                           166846.85   5461876.01
             Finished Goods                           212985.88   8047779.03
             Intercompany Receivables                 209697.72   7250566.05
             Land & Improvements                       62531.21    776722.78
             Leasehold Improvements                    53765.79    665823.25
             Machinery & Equipment                     62495.25    770645.18
             Office Furniture & Equipment             365375.19   4523550.63
             Other Assets                             114001.93   1420855.41
             Other Receivables                         31805.37   1132486.52
             Prepaid Expenses                         112642.63   3643451.17
             Raw Materials                            308472.00  11111802.00
             Trade Receivables                       1085311.52  36438197.31
             Work in Process                          176270.00   7565009.00
Balances     Headcount                                   125.00      1566.00
             Square Footage                           219500.00   3353000.00
Expenditures Amortization of Goodwill                   3646.49     53508.68
             Building Leasehold                        20750.02    250228.71
             Commissions                               65736.84   1409140.38
             Conferences                                1994.19     23853.46
             Discounts                                      NaN   1136534.22
             Employee Benefits                         59536.24    758334.80
             Entertainment                              4764.98     54986.03
             Equipment                                  1336.77     16062.72
             Furniture and Fixtures                     4550.07     55797.09
             Interest Expense                           3739.56     49755.42
             Marketing Collateral                       3906.79     88317.37
             Meals                                      6169.75     71061.44
             Office Supplies                            9154.04    105603.93
             Other Assets                               3964.79     48059.74
             Other Expenses                             5609.81     66262.19
             Other Travel Related                        699.61      8688.80
             Payroll Taxes                             77921.40   1018888.60
             Professional Services                      6258.62     74850.76
             Rent                                      18286.11    215743.21
             Returns and Adjustments                   20103.70   1419334.74
             Salaries                                 811352.20  10466921.47
             Standard Cost of Sales                   491924.36  14851504.67
             Taxes                                     39649.14   1863762.18
             Telephone                                 23521.66    415905.85
             Travel Lodging                            12105.08    140014.49
             Travel Transportation                     13230.84    152914.37
             Utilities                                 18223.37    215143.05
             Variances                                 44536.85   1242669.96
             Vehicles                                  13109.58    156682.67
Flow         Units                                       820.00     28301.00
Liabilities  Accounts Payable                         817330.11  10791892.52
             Additional Paid In Capital             -2892835.32  43540088.91
             Current Installments of Long-term Debt    99611.04   1233965.41
             Current Retained Earnings               -247985.57  28932026.27
             Insurance                                146490.16   1802941.27
             Intercompany Payables                     77204.66   2545684.25
             Long Term Obligations                    157031.39   6188911.22
             Notes Payable                             94316.50   1222709.38
             Other Current Liabilities                183214.98   6860317.75
             Other Long Term Liabilities              137639.37   1784353.33
             Other Retirement Benefits                325225.66   4197082.66
             Partner Capital                         2150000.00   2150000.00
             Pension Liability                        154978.13   1903067.39
             Prior Year Retained Earnings            2303443.30   6774671.22
             Salary & Other Comp                      333807.10   4102822.00
             Warranties                               125253.17   1504577.55
Revenue      Curr Xchg Gain/(Loss)                          NaN     97353.00
             Gain/Loss on Sales of Asset               -2984.20    -39720.65
             Intercompany Sales                        41603.64   2095377.92
             Interest Income                            2433.67     32405.60
             Other Income                               4989.36    -21256.92
             Trade Sales                             1403164.82  48114780.58


TransactionYear                                             2012         2013
AccountType  AccountDescription
Assets       Allowance for Bad Debt                   1138665.85   1340118.55
             Buildings & Improvements                 3521376.09   4465514.57
             Cash                                    53246589.35  59439815.62
             Construction In Progress                  391014.52    496081.66
             Deferred Taxes                           8459638.86   9957982.22
             Finished Goods                          12056660.42  14175242.09
             Intercompany Receivables                11264605.79  13381414.71
             Land & Improvements                      1105070.82   1401363.15
             Leasehold Improvements                    947455.73   1203683.07
             Machinery & Equipment                    1096183.44   1400604.36
             Office Furniture & Equipment             6717035.84   8921591.67
             Other Assets                             1998305.21   2546843.03
             Other Receivables                        1764455.34   2081566.37
             Prepaid Expenses                         5677895.80   6734872.08
             Raw Materials                           17762760.00  20147937.00
             Trade Receivables                       56934500.29  67006612.95
             Work in Process                         11474986.00  13747181.00
Balances     Headcount                                   2302.00      3009.00
             Square Footage                           4347000.00   4244500.00
Expenditures Amortization of Goodwill                   31693.24     47062.27
             Building Leasehold                        178437.10    277742.24
             Commissions                              1088268.59   1413457.80
             Conferences                                16421.90     25865.35
             Discounts                                 897335.04    482348.89
             Employee Benefits                         772803.04    937670.38
             Entertainment                              37983.86     59760.06
             Equipment                                  11226.17     17439.72
             Furniture and Fixtures                     39045.77     60767.40
             Interest Expense                           73685.36     98543.25
             Marketing Collateral                       68696.59     84070.96
             Meals                                      50529.39     79687.68
             Office Supplies                            71451.46    111988.16
             Other Assets                               33911.53     52822.48
             Other Expenses                             46123.20     71043.54
             Other Travel Related                       11050.26     17401.82
             Payroll Taxes                            1036598.40   1260986.00
             Professional Services                      80833.96    115677.52
             Rent                                      153743.30    238773.82
             Returns and Adjustments                  1460573.81   1190729.98
             Salaries                                10220786.23  12198229.33
             Standard Cost of Sales                   8866493.74  12149268.84
             Taxes                                    2921485.87   2418893.82
             Telephone                                 329246.05    441244.04
             Travel Lodging                             99313.06    156724.85
             Travel Transportation                     109234.11    172392.03
             Utilities                                 152958.31    238628.42
             Variances                                1858721.08   1502779.48
             Vehicles                                  110483.98    171950.77
Flow         Units                                      76982.00     95220.00
Liabilities  Accounts Payable                        15186496.19  19459702.05
             Additional Paid In Capital              63450869.15  78554374.79
             Current Installments of Long-term Debt   1743669.83   2216778.84
             Current Retained Earnings               55197427.11  64077403.70
             Insurance                                2555949.88   3250348.34
             Intercompany Payables                    3945415.93   4702682.53
             Long Term Obligations                   10174152.41  12780023.48
             Notes Payable                            1723981.34   2212302.81
             Other Current Liabilities               11398059.93  14135850.71
             Other Long Term Liabilities              2515881.50   3228532.75
             Other Retirement Benefits                6151786.85   8257484.53
             Partner Capital                          3100000.00   1175000.00
             Pension Liability                        2709353.34   3426605.13
             Prior Year Retained Earnings             7387752.00          NaN
             Salary & Other Comp                      6157004.00   8246276.26
             Warranties                               2159399.89   2725058.18
Revenue      Curr Xchg Gain/(Loss)                       4643.00    -15512.00
             Gain/Loss on Sales of Asset               -58726.23    -78577.60
             Intercompany Sales                       1697584.69   1901824.53
             Interest Income                            47995.92     64167.09
             Other Income                               94086.81    145364.20
             Trade Sales                             35958587.59  42628185.20

In [13]:
summary.index.get_level_values(0)

Index(['Assets', 'Assets', 'Assets', 'Assets', 'Assets', 'Assets', 'Assets',
       'Assets', 'Assets', 'Assets', 'Assets', 'Assets', 'Assets', 'Assets',
       'Assets', 'Assets', 'Assets', 'Balances', 'Balances', 'Expenditures',
       'Expenditures', 'Expenditures', 'Expenditures', 'Expenditures',
       'Expenditures', 'Expenditures', 'Expenditures', 'Expenditures',
       'Expenditures', 'Expenditures', 'Expenditures', 'Expenditures',
       'Expenditures', 'Expenditures', 'Expenditures', 'Expenditures',
       'Expenditures', 'Expenditures', 'Expenditures', 'Expenditures',
       'Expenditures', 'Expenditures', 'Expenditures', 'Expenditures',
       'Expenditures', 'Expenditures', 'Expenditures', 'Expenditures', 'Flow',
       'Liabilities', 'Liabilities', 'Liabilities', 'Liabilities',
       'Liabilities', 'Liabilities', 'Liabilities', 'Liabilities',
       'Liabilities', 'Liabilities', 'Liabilities', 'Liabilities',
       'Liabilities', 'Liabilities', 'Liabilities', 'Liabilities', 'Revenue',
       'Revenue', 'Revenue', 'Revenue', 'Revenue', 'Revenue'],
      dtype='object', name='AccountType')

In [14]:
summary.index.names

FrozenList(['AccountType', 'AccountDescription'])

In [15]:
summary.index.get_level_values('AccountDescription')

Index(['Allowance for Bad Debt', 'Buildings & Improvements', 'Cash',
       'Construction In Progress', 'Deferred Taxes', 'Finished Goods',
       'Intercompany Receivables', 'Land & Improvements',
       'Leasehold Improvements', 'Machinery & Equipment',
       'Office Furniture & Equipment', 'Other Assets', 'Other Receivables',
       'Prepaid Expenses', 'Raw Materials', 'Trade Receivables',
       'Work in Process', 'Headcount', 'Square Footage',
       'Amortization of Goodwill', 'Building Leasehold', 'Commissions',
       'Conferences', 'Discounts', 'Employee Benefits', 'Entertainment',
       'Equipment', 'Furniture and Fixtures', 'Interest Expense',
       'Marketing Collateral', 'Meals', 'Office Supplies', 'Other Assets',
       'Other Expenses', 'Other Travel Related', 'Payroll Taxes',
       'Professional Services', 'Rent', 'Returns and Adjustments', 'Salaries',
       'Standard Cost of Sales', 'Taxes', 'Telephone', 'Travel Lodging',
       'Travel Transportation', 'Utilities', 'Variances', 'Vehicles', 'Units',
       'Accounts Payable', 'Additional Paid In Capital',
       'Current Installments of Long-term Debt', 'Current Retained Earnings',
       'Insurance', 'Intercompany Payables', 'Long Term Obligations',
       'Notes Payable', 'Other Current Liabilities',
       'Other Long Term Liabilities', 'Other Retirement Benefits',
       'Partner Capital', 'Pension Liability', 'Prior Year Retained Earnings',
       'Salary & Other Comp', 'Warranties', 'Curr Xchg Gain/(Loss)',
       'Gain/Loss on Sales of Asset', 'Intercompany Sales', 'Interest Income',
       'Other Income', 'Trade Sales'],
      dtype='object', name='AccountDescription')

In [16]:
summary.index.get_level_values(0)

Index(['Assets', 'Assets', 'Assets', 'Assets', 'Assets', 'Assets', 'Assets',
       'Assets', 'Assets', 'Assets', 'Assets', 'Assets', 'Assets', 'Assets',
       'Assets', 'Assets', 'Assets', 'Balances', 'Balances', 'Expenditures',
       'Expenditures', 'Expenditures', 'Expenditures', 'Expenditures',
       'Expenditures', 'Expenditures', 'Expenditures', 'Expenditures',
       'Expenditures', 'Expenditures', 'Expenditures', 'Expenditures',
       'Expenditures', 'Expenditures', 'Expenditures', 'Expenditures',
       'Expenditures', 'Expenditures', 'Expenditures', 'Expenditures',
       'Expenditures', 'Expenditures', 'Expenditures', 'Expenditures',
       'Expenditures', 'Expenditures', 'Expenditures', 'Expenditures', 'Flow',
       'Liabilities', 'Liabilities', 'Liabilities', 'Liabilities',
       'Liabilities', 'Liabilities', 'Liabilities', 'Liabilities',
       'Liabilities', 'Liabilities', 'Liabilities', 'Liabilities',
       'Liabilities', 'Liabilities', 'Liabilities', 'Liabilities', 'Revenue',
       'Revenue', 'Revenue', 'Revenue', 'Revenue', 'Revenue'],
      dtype='object', name='AccountType')

In [17]:
summary[summary.index.get_level_values(0) =='Assets']

                                              Amount               \
TransactionYear                                 2010         2011
AccountType AccountDescription
Assets      Allowance for Bad Debt          21704.06    728735.78
            Buildings & Improvements       199257.40   2475051.42
            Cash                           759504.79  33247692.29
            Construction In Progress        22057.09    274867.30
            Deferred Taxes                 166846.85   5461876.01
            Finished Goods                 212985.88   8047779.03
            Intercompany Receivables       209697.72   7250566.05
            Land & Improvements             62531.21    776722.78
            Leasehold Improvements          53765.79    665823.25
            Machinery & Equipment           62495.25    770645.18
            Office Furniture & Equipment   365375.19   4523550.63
            Other Assets                   114001.93   1420855.41
            Other Receivables               31805.37   1132486.52
            Prepaid Expenses               112642.63   3643451.17
            Raw Materials                  308472.00  11111802.00
            Trade Receivables             1085311.52  36438197.31
            Work in Process                176270.00   7565009.00


TransactionYear                                  2012         2013
AccountType AccountDescription
Assets      Allowance for Bad Debt         1138665.85   1340118.55
            Buildings & Improvements       3521376.09   4465514.57
            Cash                          53246589.35  59439815.62
            Construction In Progress        391014.52    496081.66
            Deferred Taxes                 8459638.86   9957982.22
            Finished Goods                12056660.42  14175242.09
            Intercompany Receivables      11264605.79  13381414.71
            Land & Improvements            1105070.82   1401363.15
            Leasehold Improvements          947455.73   1203683.07
            Machinery & Equipment          1096183.44   1400604.36
            Office Furniture & Equipment   6717035.84   8921591.67
            Other Assets                   1998305.21   2546843.03
            Other Receivables              1764455.34   2081566.37
            Prepaid Expenses               5677895.80   6734872.08
            Raw Materials                 17762760.00  20147937.00
            Trade Receivables             56934500.29  67006612.95
            Work in Process               11474986.00  13747181.00

In [18]:
summary[(summary.index.get_level_values(0) =='Assets') | (summary.index.get_level_values(0) =='Balances')]

                                              Amount               \
TransactionYear                                 2010         2011
AccountType AccountDescription
Assets      Allowance for Bad Debt          21704.06    728735.78
            Buildings & Improvements       199257.40   2475051.42
            Cash                           759504.79  33247692.29
            Construction In Progress        22057.09    274867.30
            Deferred Taxes                 166846.85   5461876.01
            Finished Goods                 212985.88   8047779.03
            Intercompany Receivables       209697.72   7250566.05
            Land & Improvements             62531.21    776722.78
            Leasehold Improvements          53765.79    665823.25
            Machinery & Equipment           62495.25    770645.18
            Office Furniture & Equipment   365375.19   4523550.63
            Other Assets                   114001.93   1420855.41
            Other Receivables               31805.37   1132486.52
            Prepaid Expenses               112642.63   3643451.17
            Raw Materials                  308472.00  11111802.00
            Trade Receivables             1085311.52  36438197.31
            Work in Process                176270.00   7565009.00
Balances    Headcount                         125.00      1566.00
            Square Footage                 219500.00   3353000.00


TransactionYear                                  2012         2013
AccountType AccountDescription
Assets      Allowance for Bad Debt         1138665.85   1340118.55
            Buildings & Improvements       3521376.09   4465514.57
            Cash                          53246589.35  59439815.62
            Construction In Progress        391014.52    496081.66
            Deferred Taxes                 8459638.86   9957982.22
            Finished Goods                12056660.42  14175242.09
            Intercompany Receivables      11264605.79  13381414.71
            Land & Improvements            1105070.82   1401363.15
            Leasehold Improvements          947455.73   1203683.07
            Machinery & Equipment          1096183.44   1400604.36
            Office Furniture & Equipment   6717035.84   8921591.67
            Other Assets                   1998305.21   2546843.03
            Other Receivables              1764455.34   2081566.37
            Prepaid Expenses               5677895.80   6734872.08
            Raw Materials                 17762760.00  20147937.00
            Trade Receivables             56934500.29  67006612.95
            Work in Process               11474986.00  13747181.00
Balances    Headcount                         2302.00      3009.00
            Square Footage                 4347000.00   4244500.00

In [19]:
summary[summary.index.get_level_values(0) =='Assets'].sum()

        TransactionYear
Amount  2010               3.964725e+06
        2011               1.255351e+08
        2012               1.955572e+08
        2013               2.284484e+08
dtype: float64

In [20]:
summary[summary.index.get_level_values(1) =='Cash']

                                   Amount                            \
TransactionYear                      2010         2011         2012
AccountType AccountDescription
Assets      Cash                759504.79  33247692.29  53246589.35


TransactionYear                        2013
AccountType AccountDescription
Assets      Cash                59439815.62

In [21]:
summary.loc[('Assets','Allowance for Bad Debt')]

        TransactionYear
Amount  2010                 21704.06
        2011                728735.78
        2012               1138665.85
        2013               1340118.55
Name: (Assets, Allowance for Bad Debt), dtype: float64